using System.Collections.Generic;
using TaxOmbud.Domain.Common;

namespace TaxOmbud.Domain.Entities.Identity;

/// <summary>
/// Represents a discrete permission derived from a Module + Action combination.
/// All permissions are auto-generated by the DataSeeder from the Modules × PermissionAction enum matrix.
/// </summary>
public class Permission : BaseAuditableEntity
{
    /// <summary>The application module this permission applies to.</summary>
    public Modules Module { get; set; }

    /// <summary>The CRUD action this permission permits.</summary>
    public PermissionAction Action { get; set; }

    // Navigation
    public ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}
